# Generated by Django 4.2.20 on 2025-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('chamber', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('bills_count', models.IntegerField(blank=True, null=True)),
                ('rss_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('state_code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('chamber', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('bills_count', models.IntegerField(blank=True, null=True)),
                ('rss_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('state_code', 'chamber', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('bill_number', models.CharField(db_index=True, max_length=50)),
                ('session_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('bill_url', models.URLField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('text_url', models.URLField(blank=True, max_length=500, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('last_action', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('last_action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_monitored', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_viewed_source', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-view_count', '-last_action_date'],
                'unique_together': {('state_code', 'bill_number', 'session_year')},
            },
        ),
    ]
