# Generated by Django 4.2.20 on 2025-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localNewsTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
